version: "3.6"
services:
  app:
    container_name: abihome-api
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links: 
      - mongo
  mongo:
    container_name: abihome-db
    image: mongo
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"